SELECT a.KDUNIT, a.NMUNIT, b.JMLRENST_PGRM, c.JMLRENST_KEG, d.PAGU_1, d.PAGU_2, d.PAGU_3, d.PAGU_4, d.PAGU_5, e.JMLRENJ_PRGRM, f.JMLRENJ_KEG, f.PAGU_RENJA, g.PAGU_SKPD FROM mskpd AS a 
LEFT JOIN (SELECT UNITKEY, COUNT(*) AS JMLRENST_PGRM FROM t_renstra_pgrm GROUP BY UNITKEY) AS b ON a.UNITKEY=b.UNITKEY
LEFT JOIN (SELECT UNITKEY, COUNT(*) as JMLRENST_KEG FROM t_renstra_keg GROUP BY UNITKEY) AS c ON a.UNITKEY=c.UNITKEY
LEFT JOIN (SELECT UNITKEY, sum(if(TAHUN='2021',PAGU,0)) AS PAGU_1, sum(if(TAHUN='2022',PAGU,0)) AS PAGU_2, sum(if(TAHUN='2023',PAGU,0)) AS PAGU_3, sum(if(TAHUN='2024',PAGU,0)) AS PAGU_4, sum(if(TAHUN='2025',PAGU,0)) AS PAGU_5 FROM t_renstra_dana GROUP BY UNITKEY) AS d ON a.UNITKEY=d.UNITKEY
LEFT JOIN (SELECT a.UNITKEY, COUNT(*) AS JMLRENJ_PRGRM FROM (SELECT UNITKEY, KDPRGRM from t_kegiatan_keg GROUP BY UNITKEY, KDPRGRM) AS a GROUP BY a.UNITKEY) AS e ON a.UNITKEY=e.UNITKEY
LEFT JOIN (SELECT UNITKEY, COUNT(*) AS JMLRENJ_KEG, SUM(PAGU) AS PAGU_RENJA from t_kegiatan_keg GROUP BY UNITKEY) AS f ON a.UNITKEY=f.UNITKEY
LEFT JOIN (SELECT UNITKEY, PAGU AS PAGU_SKPD FROM t_pagu_skpd WHERE KDTAHAP='1') AS g ON a.UNITKEY=g.UNITKEY
WHERE a.KDSTUNIT='3'
ORDER BY a.KDUNIT